[package]
name = "scritto"
version = "0.1.0"
authors = ["Andrew Smith <andrewchristophersmith@gmail.com>"]

[dependencies]
handlebars = "0.26"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_test = "1.0"
